### ISSUE TITLE
Export variables with prefix

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/shortify-git-revision#3]
## Current situation

```yaml
- uses: rlespinasse/shortify-git-revision@v1.x
  with:
    name: GITHUB_SHA
 ```
 
 Will make available
 
 - `GITHUB_SHA_SHORT`
 
 ## Proposition
 
 In addition to the current mode, we  add a new input `prefix`
 
 ```yaml
- uses: rlespinasse/shortify-git-revision@v1.x
  with:
    name: GITHUB_SHA
    prefix: CI_
 ```
 
 Will make available
 
 - `CI_GITHUB_SHA_SHORT`
