### ISSUE TITLE
Access values using action outputs

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/shortify-git-revision#6]
In addition to the environment variables, we want to access the values as action outputs.

```
- id: short-github-sha
  uses: rlespinasse/shortify-git-revision@v1.x
  with:
     name: GITHUB_SHA
- run: |
          echo "${{ steps.short-github-sha.outputs.value }} is the same as ${{ env.GITHUB_SHA }}"
          echo "${{ steps.short-github-sha.outputs.short }} is the same as ${{ env.GITHUB_SHA_SHORT }}"
```

The `publish-env` input (as boolean) enable us to disable the publication as an environment variable
And the `prefix` input is not used in this context.
