### ISSUE TITLE
Support shortify a git revision without a git repository or without being loaded

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/shortify-git-revision#8]
This action, in order to work, needs to have the git repository with the commit to be shortify loaded.

For example, this will not work properly without `actions/checkout` before it

```yaml
- uses: rlespinasse/shortify-git-revision@v1.x
  with:
    name: GITHUB_SHA
```
